### ISSUE TITLE
Базовый Layout

### ISSUE THREAD

**Issue by xDarKFeniXx** [Drimodaren/rick-and-morty-project#4]
Нужно создать базовый layuot всего приложения, он должен работать через router
Этот layout надо сверстать, для этого надо определиться с дизайном.

**Comment by Drimodaren** [comment]
- [ ] Достать из фигмы картинки (погуглить) засунуть в папку images в проекте
- [ ] создать в components/Layout Header,Main,Footer

**Comment by Drimodaren** [comment]
- [ ] создать scss с основными цветами (main color, main background И так далее)
